name: SAM CI/CD Pipeline

on:
  push:
    branches:
      - uat    
      - develop  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. clone source code from GitHub
      - uses: actions/checkout@v3

      # 2. install Python (SAM need Python to run), have done python

      # 3. install AWS SAM CLI
      - uses: aws-actions/setup-sam@v2

      # 4. config accses AWS
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5. SAM build & Deploy on branch
      - name: SAM Deploy
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "Deploying to UAT environment..."
            sam build -t infrastructure/template.yaml && sam deploy --config-env uat 
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "Deploying to DEV environment..."
            sam build -t infrastructure/template.yaml && sam deploy --config-env dev 
          fi
